name: CI

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
      - v*

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:
    branches:
      - main
      - v*

jobs:
    rust-test:
        name: Test on Rust ${{ matrix.rust }}
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'skip ci')"

        strategy:
          matrix:
            rust:
              - stable
              - beta
              - nightly
              - 1.65.0 # MSRV
            features:
              - --all-features
              - --no-default-features
              - --no-default-features --features alloc
              - --no-default-features --features std
              - --no-default-features --features serde
              - --no-default-features --features serde,alloc
              - --no-default-features --features serde,std

        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Cancel Previous Runs
            uses: styfle/cancel-workflow-action@0.6.0
            with:
              access_token: ${{ github.token }}

          - name: Install Rust Toolchain
            uses: actions-rs/toolchain@v1
            if: ${{ !contains(github.event.head_commit.message, 'skip test') }}
            with:
              profile: minimal
              toolchain: ${{ matrix.rust }}
              override: true
              components: rustfmt, clippy

          - name: Build
            uses: actions-rs/cargo@v1
            if: ${{ !contains(github.event.head_commit.message, 'skip test') }}
            with:
              command: build
              args: ${{ matrix.features }}

          - name: Check Format
            uses: actions-rs/cargo@v1
            if: ${{ !contains(github.event.head_commit.message, 'skip test') }}
            with:
              command: fmt
              args: --all -- --check

          - name: Lint
            uses: actions-rs/cargo@v1
            if: ${{ !contains(github.event.head_commit.message, 'skip test') }}
            with:
              command: clippy
              args: --all --all-targets ${{ matrix.features }}

          - name: Test
            uses: actions-rs/cargo@v1
            if: ${{ !contains(github.event.head_commit.message, 'skip test') }}
            with:
              command: test
              args: ${{ matrix.features }}
